---
# tasks file for roles/grafana
# - name: install gpg
#   yum:
#     name: gnupg,software-properties-common
#     state: present
#     update_cache: yes
#     cache_valid_time: 3600

- name: add grafana gpg key
  rpm_key:
    state: present
    key: "https://packages.grafana.com/gpg.key"
    validate_certs: no

- name: add grafana repository
  get_url:
    url: https://packages.grafana.com/enterprise/rpm
    dest: /etc/yum.repos.d/grafana.repo
    state: present
    validate_certs: no

- name: install grafana
  yum:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: wait for service up
  uri:
    url: "localhost:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: change admin password for grafana gui
  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0
